/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fecha_componente;

import com.sun.webkit.event.WCKeyEvent;
import java.util.Date;

/**
 *
 * @author eli
 */
public class Calendario extends javax.swing.JPanel implements java.beans.Customizer {

    int c;

    public Date getFecha1() {
        return fecha1.getDate();
    }

    public Date getFecha2() {
        return fecha2.getDate();
    }

    public void setDefineFecha1(Date f1) {
        fecha1.setDate(f1);
    }

    public void setDefineFecha2(Date f2) {
        fecha2.setDate(f2);
    }

    public void setDefineTitulo1(String t1) {
        eti1.setText(t1);
    }

    public void setDefineTitulo2(String t2) {
        eti2.setText(t2);
    }

    public Calendario() {
        c = 0;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha1 = new com.toedter.calendar.JDateChooser();
        fecha2 = new com.toedter.calendar.JDateChooser();
        eti1 = new javax.swing.JLabel();
        eti2 = new javax.swing.JLabel();

        fecha1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fecha1PropertyChange(evt);
            }
        });
        fecha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fecha1KeyPressed(evt);
            }
        });

        fecha2.setEnabled(false);

        eti1.setText("jLabel1");

        eti2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti1)
                    .addComponent(eti2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eti2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fecha1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fecha1PropertyChange
        try {
            if (c >= 1) {
                fecha2.setEnabled(true);
                fecha2.setMinSelectableDate(fecha1.getDate());

                if (fecha1.getDate().getTime() <= 1) {
                    fecha2.setEnabled(false);
                }
            }
            c++;

        } catch (Exception e) {
        }
    }//GEN-LAST:event_fecha1PropertyChange

    private void fecha1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fecha1KeyPressed
       int tecla = evt.getKeyCode();
        System.out.println(tecla);
    }//GEN-LAST:event_fecha1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eti1;
    private javax.swing.JLabel eti2;
    private com.toedter.calendar.JDateChooser fecha1;
    private com.toedter.calendar.JDateChooser fecha2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setObject(Object bean) {
    }
}
